version: "{build}"

image: Visual Studio 2015

platform:
  - x86
  - x64

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm
  - npm ci

build: off

test: off

deploy: off
