name: CI

on:
  - pull_request
  - push

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - windows-2016    # to test x86
        node_version:
          - 10
          - 12
          - 14
    steps:
      - uses: actions/checkout@v2

      - if: "!contains(matrix.os, 'windows-2016')"
        name: Install Node
        uses: aminya/setup-node@x86
        with:
          node-version: ${{ matrix.node_version }}

      - if: "contains(matrix.os, 'windows-2016')"
        name: Install Node x86
        uses: aminya/setup-node@x86
        with:
          node-version: ${{ matrix.node_version }}
          node-arch: x86

      - name: Install npm
        run: npm install -g npm

      - name: Install dependencies
        run: npm install

      - if: "!contains(matrix.os, 'windows')"
        name: Run tests 👩🏾‍💻
        run: ./bin/npm test

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
